### ISSUE TITLE
Add License to Project

### ISSUE THREAD

**Issue by soheilous** [AbdUlHamedMaree/rocket-io#1]
Hello!

Thank you for creating Rocket.io! I’m very interested in using it in my project. However, I noticed that the repository doesn’t have a license specified. Without a license, it’s unclear if using or modifying the code is legally permitted.

Would you consider adding a license? Open-source licenses like MIT or Apache 2.0 are commonly used, but any license would clarify usage rights and allow developers to adopt it more freely.

Thanks again for your work on this project!

**Comment by AbdUlHamedMaree** [comment]
Hi @soheilous, happy to hear that you're interested,
I thought that the `license` field in the `package.json` is enough, but I'll add a `LICENSE` as well.

**Comment by AbdUlHamedMaree** [comment]
Done
